{% set name = "gnutls" %}
{% set version = "3.8.7" %}

{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/v{{ major_minor }}/{{ name }}-{{ version }}.tar.xz
  sha256: fe302f2b6ad5a564bcb3678eb61616413ed5277aaf8e7bf7cdb9a95a18d9f477
  patches:
    # https://gitlab.com/gnutls/gnutls/issues/660
    - 0003-Fix-libcrypto-test-it-must-always-fail.patch
    # See https://gitlab.com/gnutls/gnutls/-/commit/f3e8eac0586a19f4dafd89f68006a536b826e65a?merge_request_iid=1866
    - revert-back-to-datefudge-for-openssl-ocsp.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=gnutls
    - {{ pin_subpackage('gnutls', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - libtool
    - make
    - pkg-config
  host:
    - gettext 0.21.0     # [osx]
    - gmp {{ gmp }}
    # nettle 3.7.3 isn't available on s390x and win-64
    - nettle 3.7
    # Optional dependencies but keep them
    - libidn2 {{ libidn2 }}
    - libtasn1 4.19
    - libunistring 1.3
    - ca-certificates 2024.12.31
  run:
    - gettext >=0.19.8.1     # [osx]
    - ca-certificates

test:
  commands:
    - test -f ${PREFIX}/lib/libgnutls${SHLIB_EXT}    # [unix]
    - test -f ${PREFIX}/lib/libgnutlsxx${SHLIB_EXT}  # [unix]
    - certtool --version
    - gnutls-cli --version
    - gnutls-cli-debug --version
    - ocsptool --version
    - psktool --version

about:
  home: https://www.gnutls.org/index.html
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: GnuTLS is a secure communications library implementing the SSL, TLS and DTLS protocols
  description: |
    GnuTLS is a secure communications library implementing the SSL, TLS and DTLS protocols
    and technologies around them. It provides a simple C language application programming interface (API)
    to access the secure communications protocols as well as APIs
    to parse and write X.509, PKCS #12, and other required structures.

    The project strives to provide a secure communications back-end, simple to use
    and integrated with the rest of the base Linux libraries.
    A back-end designed to work and be secure out of the box,
    keeping the complexity of TLS and PKI out of application code.
  doc_url: https://www.gnutls.org/documentation.html
  dev_url: https://gitlab.com/gnutls/gnutls/tree/master

extra:
  recipe-maintainers:
    - mingwandroid
    - sachalau
    - sdvillal
    - scopatz
